package beanForm;

/*
 * Source code generated by StrutsCodeMaker V1.12
 * @Author Angshuman
 * @Created 2/6/2003
 *
 */


import org.apache.struts.action.ActionForm;

public class JavGuiaCancellationForm extends ActionForm
{

	/**
	 * Member variable declaration
	 */

	 String guiaNumber;
	 String formnumber;
	 String useraction;
	 String docuType;
	 


	/** 
 	 * method to set the value
 	 */ 
	public void setGuiaNumber(String guiaNumber) 
	{
		this.guiaNumber = guiaNumber; 
	}  //End method setGuianumber


	/**
 	 * method to get the value
 	 * @return String 
 	 * 
 	 */
	public String getGuiaNumber()
	{ 
		return this.guiaNumber;
	}  //End method getGuianumber


	/** 
 	 * method to set the value 
 	 */
	public void setFormnumber(String formnumber) 
	{
		this.formnumber = formnumber; 
	}  //End method setFormnumber


	/**
 	 * method to get the value
 	 * @return String 
 	 * 
 	 */
	public String getFormnumber()
	{ 
		return this.formnumber;
	}  //End method getFormnumber


	

	/** 
 	 * method to set the value 
 	 */
	public void setUseraction(String userAction) 
	{
		this.useraction = userAction; 
	}  //End method setUseraction


	/**
 	 * method to get the value
 	 *
 	 */
	public String getUseraction()
	{ 
		return this.useraction;
	}  //End method getUseraction


	public String getDocuType() {
		return docuType;
	}


	public void setDocuType(String docuType) {
		this.docuType = docuType;
	}


	

} //End class



