## Web Booking Labels

label.UserName=Usuario
label.Password=Contraseña

## Web Booking Button Labels

button.submit=Submit
button.reset=Reset

login.failed=ERROR AL INGRESAR, INTENTE DE NUEVO
login.centrocosto=USUARIO SIN CENTRO DE COSTO RELACIONADO
login.err001=USUARIO SIN CLIENTE ASOCIADO
login.err002=CLIENTE SIN CONVENIO ASOCIADO
login.success=Login success
login.logout=SE CERRO LA SESION CORRECTAMENTE

password.changed=LA CONTRASEÑA HA SIDO CAMBIADA
password.notchanged=LA CONTRASEÑA NO HA SIDO CAMBIADA
