######################  Database Specific details
### Oracle specific properties. Change this properties for other database

#dbUrl = jdbc:oracle:thin:username/password@ipaddress:port:sid //Example

# Connect Properties for PE

## Testing 

#old testing db properties commented on 29-10-2010 at 12:30pm
#dbUrl=jdbc:oracle:thin:sipprb/sip2@192.168.10.224:1521:sipprb

#DESARROLLO
#dbUrl=jdbc:oracle:thin:SIPWEB2/plmmdev@192.168.10.52:1521:sipdev

#NUEVO TEST
#dbUrl=jdbc:oracle:thin:SIPTEST/t35t52@192.168.10.52:1521:sipdev

#QA
#dbUrl=jdbc:oracle:thin:SIPQA/qu452@192.168.10.52:1521:sipdev

## Production
dbUrl=jdbc:oracle:thin:sipweb2/wmoy0412p@192.168.10.20:1521:sipweb

driver=oracle.jdbc.driver.OracleDriver
maxConnections=25
dataSource = jdbc/webbooking
pathFileXls = \\\\192.168.10.230\\webbookingUpload

#link generacion pdf de carta porte
#LOCAL
#cartaPorteInt=http://localhost:8081/wsReportPaquetexpress/
endPointDocInt=http://localhost:8080/wsPaquetexpress/services/DocumentacionSOAP
endPointGuiaRetorno=http://localhost:8080/wsPaquetexpress/services/GuiasRetornoSOAP

#DESARROLLO INTERNO
cartaPorteInt=http://192.168.10.230:8082/wsReportPaquetexpress/
#endPointDocInt=http://192.168.10.230:8082/wsPaquetexpress/services/DocumentacionSOAP
#endPointGuiaRetorno=http://192.168.10.230:8082/wsPaquetexpress/services/GuiasRetornoSOAP
apiLoginLDAPInt=http://wldev.paquetexpress.mx:7007/signPAQX/
#apiLoginLDAPInt=http://192.168.10.230:8082/SignAppPAQX/
apibrncOCUInt=http://wldev.paquetexpress.mx:7007/RadRestFul/

#DESARROLLO EXTERNO
cartaPorteExt=http://192.168.10.230:8082/wsReportPaquetexpress/
endPointDocExt=http://192.168.10.230:8082/wsPaquetexpress/services/DocumentacionSOAP
#apiLoginLDAPExt=http://wldev.paquetexpress.mx:7007/signPAQX/
#apiLoginLDAPExt=http://192.168.10.230:8082/SignAppPAQX/
apibrncOCUExt=http://wldev.paquetexpress.mx:7007/RadRestFul/


#PRUEBAS INTERNO
#cartaPorteInt=http://192.168.10.43:8082/wsReportPaquetexpress/
#endPointDocInt=http://192.168.10.43:8082/wsPaquetexpress/services/DocumentacionSOAP
#endPointGuiaRetorno=http://192.168.10.43:8082/wsPaquetexpress/services/GuiasRetornoSOAP
#apiLoginLDAPInt=http://test_glp.paquetexpress.mx:8007/signPAQX/

#PRUEBAS EXTERNO
#cartaPorteExt=http://187.141.146.59:8082/wsReportPaquetexpress/
#endPointDocExt=http://192.168.10.43:8082/wsPaquetexpress/services/DocumentacionSOAP
#apiLoginLDAPExt=http://test_glp.paquetexpress.com.mx:8007/signPAQX/

#QA INTERNO
#cartaPorteInt=http://192.168.10.230:8083/wsReportPaquetexpress/
#endPointDocInt=http://localhost:8083/wsPaquetexpress/services/DocumentacionSOAP
#endPointGuiaRetorno=http://localhost:8083/wsPaquetexpress/services/GuiasRetornoSOAP
apiLoginLDAPInt=http://qaglp.paquetexpress.mx:7007/signPAQX/
#apibrncOCUInt=http://qaglp.paquetexpress.mx:7007/RadRestFul/

#QA EXTERNO
#cartaPorteExt=http://192.168.10.230:8083/wsReportPaquetexpress/
#endPointDocExt=http://localhost:8083/wsPaquetexpress/services/DocumentacionSOAP
apiLoginLDAPExt=http://qaglp.paquetexpress.mx:7007/signPAQX/
#apibrncOCUExt=http://qaglp.paquetexpress.mx:7007/RadRestFul/

#PRODUCCION INTERNO
#cartaPorteInt=http://webbooking.paquetexpress.com.mx:8104/wsReportPaquetexpress/
#endPointDocInt=http://192.168.10.51:8082/wsPaquetexpress/services/DocumentacionSOAP
#endPointGuiaRetorno=http://192.168.10.51:8082/wsPaquetexpress/services/GuiasRetornoSOAP
#apiLoginLDAPInt=http://glp.paquetexpress.mx:7007/signPAQX/

#PRODUCCION EXTERNO
#cartaPorteExt=http://webbooking.paquetexpress.com.mx:8104/wsReportPaquetexpress/
#endPointDocExt=http://192.168.10.51:8082/wsPaquetexpress/services/DocumentacionSOAP
#apiLoginLDAPExt=http://glp.paquetexpress.com.mx:7007/signPAQX/