notificacionSMSPiso=Paquetexpress informa: estimado cliente, se ha solicitado una guia de retorno: @guiaRetorno
notificacionSMSRecoleccion=Paquetexpress informa: estimado Cliente, se ha solicitado una guia de retorno con una solicitud de recoleccion: @guiaRetorno
#Link para enviar notificaciones por email o/y telefono celular
endPointNotificacion=http://jobs.paquetexpress.mx:8001
estructuraEmailParteAsunto=Paquetexpress te informa @cliente