

/*
 * Source code generated by StrutsCodeMaker V1.12
 * @Author Ravindran Ramaiah
 * @Created 2/17/2003
 *
 */


import org.apache.struts.action.ActionForm;

public class JavManifestDetailsForm extends ActionForm
{
	
	/**
	 * Member variable declaration
	 */

	 protected String maxPageIndex;
	 protected String pageIndex;
	 protected String currentPage;
	 protected String next;
	 protected String previous;
	 protected String endIndex;
	 protected String startIndex;
	 private String operation="";


	/** 
 	 * method to set the value 
 	 */
	public void setMaxpageindex(String maxPageIndex) 
	{
		this.maxPageIndex = maxPageIndex; 
	}  //End method setMaxpageindex


	/**
 	 * method to get the value
 	 *
 	 */
	public String getMaxpageindex()
	{ 
		return this.maxPageIndex;
	}  //End method getMaxpageindex


	/** 
 	 * method to set the value 
 	 */
	public void setPageindex(String pageIndex) 
	{
		this.pageIndex = pageIndex; 
	}  //End method setPageindex


	/**
 	 * method to get the value
 	 *
 	 */
	public String getPageindex()
	{ 
		return this.pageIndex;
	}  //End method getPageindex


	/** 
 	 * method to set the value 
 	 */
	public void setCurrentpage(String currentPage) 
	{
		this.currentPage = currentPage; 
	}  //End method setCurrentpage


	/**
 	 * method to get the value
 	 */
	public String getCurrentpage()
	{ 
		return this.currentPage;
	}  //End method getCurrentpage


	/** 
 	 * method to set the value 
 	 */
	public void setNext(String next) 
	{
		this.next = next; 
	}  //End method setNext


	/**
 	 * method to get the value
 	 *
 	 */
	public String getNext()
	{ 
		return this.next;
	}  //End method getNext


	/** 
 	 * method to set the value 
 	 */
	public void setPrevious(String previous) 
	{
		this.previous = previous; 
	}  //End method setPrevious


	/**
 	 * method to get the value
 	 */
	public String getPrevious()
	{ 
		return this.previous;
	}  //End method getPrevious


	/** 
 	 * method to set the value 
 	 */
	public void setEndindex(String endIndex) 
	{
		this.endIndex = endIndex; 
	}  //End method setEndindex


	/**
 	 * method to get the value
 	 */
	public String getEndindex()
	{ 
		return this.endIndex;
	}  //End method getEndindex


	/** 
 	 * method to set the value 
 	 */
	public void setStartindex(String startIndex) 
	{
		this.startIndex = startIndex; 
	}  //End method setStartindex


	/**
 	 * method to get the value
 	 *
 	 */
	public String getStartindex()
	{ 
		return this.startIndex;
	}  //End method getStartindex
	
	public void setOperation(String opr){
		this.operation = opr;
	}
	
	public String getOperation(){
		return this.operation;
	}

} //End class
